
[versions]
kotlin = "2.2.21"
androidGradlePlugin = "9.0.0-beta03"
compileSdk = "36"
minSdk = "23"
targetSdk = "36"
versionCode = "24"
javaVersion = "17"
material = "1.13.0"
coreKtx = "1.17.0"
appcompat = "1.7.1"
activityKtx = "1.12.1"
fragmentKtx = "1.8.9"
okhttp = "5.3.2"
junit = "4.13.2"
espressoCore = "3.7.0"
composeBom = "2024.05.00"
activityCompose = "1.9.0"
composeMaterial3 = "1.2.1"

[libraries]
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
material = { module = "com.google.android.material:material", version.ref = "material" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
junit = { module = "junit:junit", version.ref = "junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
